---
- hosts: web
  roles:
      - ansistrano.deploy
  vars:
      ansistrano_deploy_from: "{{ playbook_dir }}/.."
      ansistrano_deploy_to: "/opt/www/webapp"
      ansistrano_version_dir: "releases"
      ansistrano_current_dir: "current"
      ansistrano_current_via: "symlink"
      ansistrano_keep_releases: 5

      ansistrano_shared_paths: []
      ansistrano_shared_files: []

      ansistrano_ensure_shared_paths_exist: yes
      ansistrano_ensure_basedirs_shared_files_exist: yes

      ansistrano_deploy_via: "rsync"
      ansistrano_allow_anonymous_stats: no

      ansistrano_rsync_extra_params: ""
      ansistrano_rsync_set_remote_user: yes
      ansistrano_rsync_path: ""
      ansistrano_rsync_use_ssh_args: no
